### ISSUE TITLE
Secronom_lore error

### ISSUE THREAD

**Issue by T3hBoy** [Kenan2000/BrightNights-Structured-Kenan-Modpack#107] opened 2022-07-06 23:42 UTC
Hello, me again, sorry for the back-to-back inconvenience but I ran a separate test with vanilla secronom and the lore expansion, ran into this issue when finalizing the world generation. Not sure if it has to do with the recent build or not
![recent issue](https://user-images.githubusercontent.com/108841169/177660578-978471c4-30fd-439d-adf7-69f80f98b22f.png)

Once again, my apologies for the inconvenience

**Comment by Nitsua1230** [comment] 2022-07-06 23:46
I can confirm this issue. Looks like the last update push deleted most of the npc classes. Downloading the previous version of the pack and replacing secro_npc.json gets that to procede for me.

**Comment by Kenan2000** [comment] 2022-07-07 16:38
@T3hBoy @Nitsua1230 Hopefully fixed in this update as well

**Closed by Kenan2000** 2022-07-07 16:38 UTC
