### ISSUE TITLE
Wrist computer activates photo taking on endless loop when using music function via computer systems, won't play music otherwise

### ISSUE THREAD

**Issue by yay855** [Kenan2000/BrightNights-Structured-Kenan-Modpack#143] opened 2023-01-22 15:52 UTC
When I try to activate music via the wrist computer, it does nothing but still gives the message. When I download music from an SD card and play it via the computer interface, it brings up the camera menu instead... on loop, so pressing escape just reopens it, all while giving messages about both the camera and the geiger counter every time it reopens. You literally have to force-quit the game when this happens.

**Comment by Kenan2000** [comment] 2023-01-27 23:41
I have linted this file, added wrist_comp_budget_music transform to wrist_comp_budget, also I've added a correct revert transform to wrist_comp_budget_music so that it reverts to wrist_comp_budget correctly, see if this item in mod works hopefully

**Comment by yay855** [comment] 2023-01-29 11:37
No, that did not fix it.

**Comment by zantanzuken** [comment] 2023-06-02 22:34
i can both confirm and deny this is a thing still... i've had it happen to me before while i was cycling through downloading new stuff from SD cards and accidentally pressed play music, putting me in that loop, but i've opened up the wrist computer and just hit play music not thinking about it and it worked properly as intended.

**Comment by Kenan2000** [comment] 2023-09-05 13:52
Hmm, considering that this seems like a hardcode error, because JSON is made in a very careful non-hacky way which I can testify genuinely because I have tried to fix this, I will close this

**Closed by Kenan2000** 2023-09-05 13:52 UTC
